# add the linters you want stickler to use for this project
linters:
  stylelint:
    # indicate where is the config file for stylelint
    config: "stylelint.config.js"
files:
  ignore:
    - "assets/css/reset.css"
